### ISSUE TITLE
Board logic

### ISSUE THREAD

**Issue by burunyuu23** [burunyuu23/imageboardAPI#1]
### Tasks
- [ ] Get all boards with their themes
- [ ] Get board with fully description, banner (like main message) + 10 threads (pagination, sort by new/old/by watch popular/by discussion)
- [x] #7 Get random board (from all/theme)
