### ISSUE TITLE
Thread logic

### ISSUE THREAD

**Issue by burunyuu23** [burunyuu23/imageboardAPI#2]
### Tasks
- [x] #10 Get pagination threads + sort by new/old/by watch popular/by discussion (message count + message per day)
- [x] #13 Get thread + main message + pagination message
- [X] #8  Get random thread (from all/theme/board) 
- [x] #4
