### ISSUE TITLE
Message logic

### ISSUE THREAD

**Issue by burunyuu23** [burunyuu23/imageboardAPI#3]
### Tasks
- [x] Get all messages (pagination)
- [x] #11 sort by new/old
- [x] Get message by id
- [x] #9 Get random message (from all/theme/board/thread) (with replies/responses) 
- [x] #5
